# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-GPG
version:      1.59
version_from: GPG.pm
installdirs:  site
requires:
    Carp:                          0
    Date::Parse:                   0
    Fcntl:                         0
    File::Path:                    0
    File::Temp:                    0
    IPC::Run:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
